<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'category_id' => Category::where('name_english', 'Breakfast')->first()->id,
                'name_dutch' => 'Ochtend Boost Smoothie Bowl',
                'description_dutch' => 'Een mix van acai, banaan en gemengde bessen, gegarneerd met granola, chiazaad en kokosvlokken.',
                'name_english' => 'Morning Boost Smoothie Bowl',
                'description_english' => 'A blend of acai, banana, and mixed berries topped with granola, chia seeds, and coconut flakes.',
                'name_german' => 'Morgen Boost Smoothie Bowl',
                'description_german' => 'Eine Mischung aus Acai, Banane und gemischten Beeren, garniert mit Müsli, Chiasamen und Kokosflocken.',
                'price' => 4.50,    
                'kcal' => 300,
            ],
            [
                'category_id' => Category::where('name_english', 'Breakfast')->first()->id,
                'name_dutch' => 'Eiercellent Wrap',
                'description_dutch' => 'Volkorenwrap gevuld met roerei, spinazie en een lichte saus op basis van yoghurt.',
                'name_english' => 'Eggcellent Wrap',
                'description_english' => 'Whole-grain wrap filled with scrambled eggs, spinach, and a light yogurt-based sauce.',
                'name_german' => 'Eierartiger Wrap',
                'description_german' => 'Vollkorn-Wrap gefüllt mit Rührei, Spinat und einer leichten Sauce auf Joghurtbasis.',
                'price' => 3.50,
                'kcal' => 250,
            ],
            [
                'category_id' => Category::where('name_english', 'Breakfast')->first()->id,
                'name_dutch' => 'Pindakaas Power Toast',
                'description_dutch' => 'Volkorenbrood met natuurlijke pindakaas en plakjes banaan.',
                'name_english' => 'Peanut Butter Power Toast',
                'description_english' => 'Whole-grain toast with natural peanut butter and banana slices.',
                'name_german' => 'Erdnussbutter Power Toast',
                'description_german' => 'Vollkorntoast mit natürlicher Erdnussbutter und Bananenscheiben.',
                'price' => 2.80,
                'kcal' => 220,
            ],
            [
                'category_id' => Category::where('name_english', 'Lunch & Dinner')->first()->id,
                'name_dutch' => 'Eiwitrijke Bowl',
                'description_dutch' => 'Quinoa, gegrilde tofu, geroosterde groenten en een tahindressing.',
                'name_english' => 'Protein-Packed Bowl',
                'description_english' => 'Quinoa, grilled tofu, roasted vegetables, and a tahini dressing.',
                'name_german' => 'Proteinreiche Bowl',
                'description_german' => 'Quinoa, gegrillter Tofu, geröstetes Gemüse und ein Tahini-Dressing.',
                'price' => 6.00,
                'kcal' => 450,
            ],
            [
                'category_id' => Category::where('name_english', 'Lunch & Dinner')->first()->id,
                'name_dutch' => 'Supergroene salade',
                'description_dutch' => 'Boerenkool, spinazie, avocado, edamame, komkommer en een citroen-olijfolie vinaigrette.',
                'name_english' => 'Supergreen Salad',
                'description_english' => 'Kale, spinach, avocado, edamame, cucumber, and a lemon-olive oil vinaigrette.',
                'name_german' => 'Supergrüner Salat',
                'description_german' => 'Grünkohl, Spinat, Avocado, Edamame, Gurke und eine Zitronen-Olivenöl-Vinaigrette.',
                'price' => 5.00,
                'kcal' => 300,
            ],
            [
                'category_id' => Category::where('name_english', 'Lunch & Dinner')->first()->id,
                'name_dutch' => 'Pittige kikkererwten wrap',
                'description_dutch' => 'Volkorenwrap met gekruide kikkererwten, geraspte wortels, sla en hummus.',
                'name_english' => 'Zesty Chickpea Wrap',
                'description_english' => 'Whole-grain wrap with spiced chickpeas, shredded carrots, lettuce, and hummus.',
                'name_german' => 'Pikanter Kichererbsen-Wrap',
                'description_german' => 'Vollkorn-Wrap mit gewürzten Kichererbsen, geraspelten Karotten, Salat und Hummus.',
                'price' => 4.50,
                'kcal' => 400,
            ],
            [
                'category_id' => Category::where('name_english', 'Sides')->first()->id,
                'name_dutch' => 'Zoete aardappelpartjes',
                'description_dutch' => 'In de oven gebakken zoete aardappelpartjes, op smaak gebracht met paprika en een scheutje olijfolie.',
                'name_english' => 'Sweet Potato Wedges',
                'description_english' => 'Oven-baked sweet potato wedges seasoned with paprika and a touch of olive oil.',
                'name_german' => 'Süßkartoffelspalten',
                'description_german' => 'Im Ofen gebackene Süßkartoffelspalten, gewürzt mit Paprika und einem Schuss Olivenöl.',
                'price' => 3.50,
                'kcal' => 250,
            ],
            [
                'category_id' => Category::where('name_english', 'Sides')->first()->id,
                'name_dutch' => 'Quinoa Salade Cup',
                'description_dutch' => 'Mini kopje quinoa gemengd met komkommer, cherrytomaatjes, peterselie en citroendressing.',
                'name_english' => 'Quinoa Salad Cup',
                'description_english' => 'Mini cup of quinoa mixed with cucumber, cherry tomatoes, parsley, and lemon dressing.',
                'name_german' => 'Quinoa-Salat-Cup',
                'description_german' => 'Minitasse Quinoa gemischt mit Gurke, Kirschtomaten, Petersilie und Zitronendressing.',
                'price' => 3.00,
                'kcal' => 200,
            ],
            [
                'category_id' => Category::where('name_english', 'Sides')->first()->id,
                'name_dutch' => 'Mini Groenteschotel',
                'description_dutch' => 'Een selectie van worteltjes, selderij, komkommerschijfjes en cherrytomaatjes, geserveerd met een dip naar keuze.',
                'name_english' => 'Mini Veggie Platter',
                'description_english' => 'A selection of carrot sticks, celery, cucumber slices, and cherry tomatoes served with a dip of your choice.',
                'name_german' => 'Mini-Gemüseplatte',
                'description_german' => 'Eine Auswahl an Karottensticks, Sellerie, Gurkenscheiben und Kirschtomaten, serviert mit einem Dip Ihrer Wahl.',
                'price' => 3.00,
                'kcal' => 150,
            ],
            [
                'category_id' => Category::where('name_english', 'Sides')->first()->id,
                'name_dutch' => 'Bruine rijst en edamame bowl',
                'description_dutch' => 'Een klein portie bruine rijst met gestoomde edamame en een scheutje sojasaus.',
                'name_english' => 'Brown Rice & Edamame Bowl',
                'description_english' => 'A small portion of brown rice topped with steamed edamame and a drizzle of soy sauce.',
                'name_german' => 'Bowl aus braunem Reis und Edamame',
                'description_german' => 'Eine kleine Portion brauner Reis, garniert mit gedämpften Edamame und einem Schuss Sojasauce.',
                'price' => 3.50,
                'kcal' => 300,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Geroosterde kikkererwten',
                'description_dutch' => 'Knapperige geroosterde kikkererwten met pittige paprika- of kruidenkruiden naar keuze.',
                'name_english' => 'Roasted Chickpeas',
                'description_english' => 'Crunchy roasted chickpeas with your choice of spicy paprika or herb seasoning.',
                'name_german' => 'Geröstete Kichererbsen',
                'description_german' => 'Knusprig geröstete Kichererbsen mit scharfer Paprika- oder Kräuterwürze nach Wahl.',
                'price' => 2.50,
                'kcal' => 180,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Trailmix Cup',
                'description_dutch' => 'Een mix van noten, gedroogd fruit en zaden voor een energieboost.',
                'name_english' => 'Trail Mix Cup',
                'description_english' => 'A mix of nuts, dried fruits, and seeds for an energy boost.',
                'name_german' => 'Studentenfutter Cup',
                'description_german' => 'Eine Mischung aus Nüssen, Trockenfrüchten und Samen für einen Energieschub.',
                'price' => 2.00,
                'kcal' => 200,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Chia Pudding Cup',
                'description_dutch' => 'Romige chiapudding gemaakt met amandelmelk en gegarneerd met vers fruit.',
                'name_english' => 'Chia Pudding Cup',
                'description_english' => 'Creamy chia pudding made with almond milk and topped with fresh fruit.',
                'name_german' => 'Chia Pudding Cup',
                'description_german' => 'Cremiger Chia-Pudding mit Mandelmilch und garniert mit frischen Früchten.',
                'price' => 3.00,
                'kcal' => 250,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Gebakken Falafelhapjes (4 stuks)',
                'description_dutch' => 'Gebakken falafelballetjes geserveerd met een dip naar keuze.',
                'name_english' => 'Baked Falafel Bites (4 pcs)',
                'description_english' => 'Baked falafel balls served with a dip of your choice.',
                'name_german' => 'Gebackene Falafel-Häppchen (4 Stück)',
                'description_german' => 'Gebackene Falafelbällchen, serviert mit einem Dip Ihrer Wahl.',
                'price' => 3.50,
                'kcal' => 220,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Mini Volkoren Broodstengels',
                'description_dutch' => 'Knapperige, voedzame broodstengels, perfect te combineren met hummus of salsa.',
                'name_english' => 'Mini Whole-Grain Breadsticks',
                'description_english' => 'Crisp, wholesome breadsticks perfect for pairing with hummus or salsa.',
                'name_german' => 'Mini Vollkorn-Brotstangen',
                'description_german' => 'Knusprige, gesunde Brotstangen, perfekt zu Hummus oder Salsa.',
                'price' => 2.00,
                'kcal' => 150,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Appel-kaneelchips',
                'description_dutch' => 'Gebakken appelschijfjes, licht bestrooid met kaneel.',
                'name_english' => 'Apple & Cinnamon Chips',
                'description_english' => 'Baked apple slices lightly dusted with cinnamon.',
                'name_german' => 'Apfel-Zimt-Chips',
                'description_german' => 'Gebackene Apfelscheiben, leicht mit Zimt bestäubt.',
                'price' => 2.50,
                'kcal' => 100,
            ],
            [
                'category_id' => Category::where('name_english', 'Snacks')->first()->id,
                'name_dutch' => 'Courgette frietjes',
                'description_dutch' => 'Gebakken courgettereepjes bedekt met een dun laagje broodkruim.',
                'name_english' => 'Zucchini Fries',
                'description_english' => 'Baked zucchini sticks coated in a light breadcrumb crust.',
                'name_german' => 'Zucchini-Pommes',
                'description_german' => 'Gebackene Zucchinisticks umhüllt mit einer leichten Semmelbröselkruste.',
                'price' => 3.00,
                'kcal' => 180,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Klassieke Hummus',
                'name_english' => 'Classic Hummus',
                'name_german' => 'Klassischer Hummus',
                'price' => 0.80,
                'kcal' => 70,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Avocado-Limetten-Dip',
                'name_english' => 'Avocado Lime Dip',
                'name_german' => 'Avocado-limoendip',
                'price' => 1.00,
                'kcal' => 80,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Griekse Yoghurt Ranch',
                'name_english' => 'Greek Yogurt Ranch',
                'name_german' => 'Griechische Joghurt-Ranch',
                'price' => 0.70,
                'kcal' => 50,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Pittige Sriracha Mayo',
                'name_english' => 'Spicy Sriracha Mayo',
                'name_german' => 'Scharfe Sriracha Mayo',
                'price' => 0.70,
                'kcal' => 60,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Knoflook-tahinsaus',
                'name_english' => 'Garlic Tahini Sauce',
                'name_german' => 'Knoblauch-Tahini-Sauce',
                'price' => 0.90,
                'kcal' => 90,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Pittige tomatensalsa',
                'name_english' => 'Zesty Tomato Salsa',
                'name_german' => 'Pikante Tomatensalsa',
                'price' => 0.60,
                'kcal' => 20,
            ],
            [
                'category_id' => Category::where('name_english', 'Dips')->first()->id,
                'name_dutch' => 'Pindasaus Dipsaus',
                'name_english' => 'Peanut Dipping Sauce',
                'name_german' => 'Erdnuss-Dip-Sauce',
                'price' => 0.90,
                'kcal' => 100,
            ],
            [
                'category_id' => Category::where('name_english', 'Drinks')->first()->id,
                'name_dutch' => 'Groene Glow Smoothie',
                'description_dutch' => 'Spinazie, ananas, komkommer en kokoswater.',
                'name_english' => 'Green Glow Smoothie',
                'description_english' => 'Spinach, pineapple, cucumber, and coconut water.',
                'name_german' => 'Grüner Glow-Smoothie',
                'description_german' => 'Spinat, Ananas, Gurke und Kokoswasser.',
                'price' => 3.50,
                'kcal' => 120,
            ],
            [
                'category_id' => Category::where('name_english', 'Drinks')->first()->id,
                'name_dutch' => 'IJskoude Matcha Latte',
                'description_dutch' => 'Licht gezoete matcha groene thee met amandelmelk.',
                'name_english' => 'Iced Matcha Latte',
                'description_english' => 'Lightly sweetened matcha green tea with almond milk.',
                'name_german' => 'Eisgekühlter Matcha Latte',
                'description_german' => 'Leicht gesüßter Matcha-Grüntee mit Mandelmilch.',
                'price' => 3.00,
                'kcal' => 90,
            ],
            [
                'category_id' => Category::where('name_english', 'Drinks')->first()->id,
                'name_dutch' => 'Fruitwater',
                'description_dutch' => 'Vers geperst water met een keuze uit citroen-munt, aardbei-basilicum of komkommer-limoen.',
                'name_english' => 'Fruit-Infused Water',
                'description_english' => 'Freshly infused water with a choice of lemon-mint, strawberry-basil, or cucumber-lime.',
                'name_german' => 'Mit Früchten angereichertes Wasser',
                'description_german' => 'Frisch aufgegossenes Wasser, wahlweise mit Zitrone-Minze, Erdbeer-Basilikum oder Gurke-Limette.',
                'price' => 1.50,
                'kcal' => 0,
            ],
            [
                'category_id' => Category::where('name_english', 'Drinks')->first()->id,
                'name_dutch' => 'Bessen Blast Smoothie',
                'description_dutch' => 'Een romige mix van aardbeien, bosbessen en frambozen met amandelmelk.',
                'name_english' => 'Berry Blast Smoothie',
                'description_english' => 'A creamy blend of strawberries, blueberries, and raspberries with almond milk.',
                'name_german' => 'Beeren-Blast-Smoothie',
                'description_german' => 'Eine cremige Mischung aus Erdbeeren, Blaubeeren und Himbeeren mit Mandelmilch.',
                'price' => 3.80,
                'kcal' => 140,
            ],
            [
                'category_id' => Category::where('name_english', 'Drinks')->first()->id,
                'name_dutch' => 'Citruskoeler',
                'description_dutch' => 'Een verfrissende mix van sinaasappelsap, bruisend water en een vleugje limoen.',
                'name_english' => 'Citrus Cooler',
                'description_english' => 'A refreshing mix of orange juice, sparkling water, and a hint of lime.',
                'name_german' => 'Zitruskühler',
                'description_german' => 'Eine erfrischende Mischung aus Orangensaft, Mineralwasser und einem Hauch Limette.',
                'price' => 3.00,
                'kcal' => 90,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
